version: 2.1
notify:
  webhooks:
    - url: https://outlook.office.com/webhook/504a268c-2467-448c-8bb2-4acc7868e43c@16a9d9bf-fe63-4826-896e-910a781c9c99/CircleCI/3ff53964a8c148479a0dffde37fc6ec6/f8956b24-66ba-48b1-8828-dafe51578a9b

jobs:
  build:
    docker:
      - image: circleci/node:14
    environment:
      API_URL: 'https://swann-studio.com/api/'
      FILE_URL: 'https://swann-studio.com/files/'
      NARRATOR_LINK: 'https://narrator-survey.swann-studio.com/'
      LOGIN_LINK: 'app'
      FRONTPAGE_VIDEO_ID: 'kaKkslEshik'
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Generate static site
          command: npx nuxt generate
      - setup_remote_docker
      - run:
          name: Locker login
          command:
            docker login -u devops -p $DOCKER_PASSWORD $DOCKER_REGISTRY
      - run:
          name: Build docker image
          command: docker build . -t $DOCKER_REGISTRY/website:latest
      - run:
          name: Push docker image
          command: docker push $DOCKER_REGISTRY/website:latest

workflow:
  delivery:
    jobs:
      - build:
          filters:
            only:
              - master
